from langchain_core.messages import BaseMessage
from langchain_groq import ChatGroq
from langgraph.graph import StateGraph, START, END
from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages
from langgraph.checkpoint.sqlite import SqliteSaver
import sqlite3
from dotenv import load_dotenv
import re

# load groq api key
load_dotenv()

# create groq chat model
llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0.2
)

# create state for the graph
class ChatState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages] 

# ******************* Utitilies Functions *******************

# create chat_mode to solve user querry
def chat_mode(state: ChatState):
    messages = state['messages']

    response = llm.invoke(messages)

    return {'messages': [response]}

# create sqlite database and connect it to the backend
conn = sqlite3.connect("chatbot.db", check_same_thread=False)
checkpointer = SqliteSaver(conn)

# --- Title Management ---
conn.execute("CREATE TABLE IF NOT EXISTS thread_titles (thread_id TEXT PRIMARY KEY, title TEXT)")
conn.commit()

def save_thread_title(thread_id: str, title: str):
    conn.execute("INSERT OR REPLACE INTO thread_titles (thread_id, title) VALUES (?, ?)", (thread_id, title))
    conn.commit()

def generate_title(user_input: str) -> str:
    prompt = f"Summarize the following prompt into a concise 3-4 word title. Do not use quotes or special characters:\n\n{user_input}"
    response = llm.invoke(prompt)
    content = response.content
    
    # Remove <think> blocks generated by reasoning models
    content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
    
    return content.strip(' "\'\n')

# to find total number of threads
def retrieve_all_threads():
    cursor = conn.execute("SELECT thread_id, title FROM thread_titles")
    titles = {row[0]: row[1] for row in cursor.fetchall()}

    all_threads = []
    seen = set()

    for checkpoint in checkpointer.list(None):
        t_id = checkpoint.config['configurable']['thread_id']
        if t_id not in seen:
            seen.add(t_id)
            all_threads.append({
                "id": t_id,
                "title": titles.get(t_id, t_id)
            })

    return all_threads


# create and compile graph
graph = StateGraph(ChatState)
graph.add_node('chat_mode', chat_mode)
graph.add_edge(START, 'chat_mode')
graph.add_edge('chat_mode', END)
chatbot = graph.compile(checkpointer=checkpointer)

